name: dart_ASE
description: A Dart package for quantum-secure encryption functionalities.
version: 1.0.0

environment:
    sdk: ">=2.19.0 <3.0.0"

dependencies:
    cryptography: ^2.7.0

dev_dependencies:
    test: ^1.26.2
